version: '3'
services:
  ssdb:
      image: registry.cn-hangzhou.aliyuncs.com/otome/ssdb
      restart: always
      tty: true
      volumes:
        - ./ssdb.conf:/usr/local/ssdb/ssdb.conf
        - ./data:/data
      ports:
        - 8888:8888
      networks:
        - web

networks: 
  web:
    driver: bridge